// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// loglik_bastide_arma
double loglik_bastide_arma(const arma::mat& R, const arma::mat& S, const arma::imat& edge, const arma::vec& edge_length, const arma::mat& traits, const arma::ivec& species_idx, int n_tips, int n_nodes);
RcppExport SEXP _phylopars_pyport_loglik_bastide_arma(SEXP RSEXP, SEXP SSEXP, SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP traitsSEXP, SEXP species_idxSEXP, SEXP n_tipsSEXP, SEXP n_nodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type traits(traitsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type species_idx(species_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_tips(n_tipsSEXP);
    Rcpp::traits::input_parameter< int >::type n_nodes(n_nodesSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_bastide_arma(R, S, edge, edge_length, traits, species_idx, n_tips, n_nodes));
    return rcpp_result_gen;
END_RCPP
}
// bastide_gradient_arma
List bastide_gradient_arma(const arma::mat& R, const arma::mat& S, const arma::imat& edge, const arma::vec& edge_length, const arma::mat& traits, const arma::ivec& species_idx, int n_tips, int n_nodes);
RcppExport SEXP _phylopars_pyport_bastide_gradient_arma(SEXP RSEXP, SEXP SSEXP, SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP traitsSEXP, SEXP species_idxSEXP, SEXP n_tipsSEXP, SEXP n_nodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type traits(traitsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type species_idx(species_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_tips(n_tipsSEXP);
    Rcpp::traits::input_parameter< int >::type n_nodes(n_nodesSEXP);
    rcpp_result_gen = Rcpp::wrap(bastide_gradient_arma(R, S, edge, edge_length, traits, species_idx, n_tips, n_nodes));
    return rcpp_result_gen;
END_RCPP
}
// em_fit_arma
List em_fit_arma(const arma::mat& R_init, const arma::mat& S_init, const arma::vec& mu_init, const arma::imat& edge, const arma::vec& edge_length, const arma::mat& traits, const arma::ivec& species_idx, int n_tips, int n_nodes, int max_iter, double tol, bool verbose);
RcppExport SEXP _phylopars_pyport_em_fit_arma(SEXP R_initSEXP, SEXP S_initSEXP, SEXP mu_initSEXP, SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP traitsSEXP, SEXP species_idxSEXP, SEXP n_tipsSEXP, SEXP n_nodesSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type R_init(R_initSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S_init(S_initSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_init(mu_initSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type traits(traitsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type species_idx(species_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_tips(n_tipsSEXP);
    Rcpp::traits::input_parameter< int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(em_fit_arma(R_init, S_init, mu_init, edge, edge_length, traits, species_idx, n_tips, n_nodes, max_iter, tol, verbose));
    return rcpp_result_gen;
END_RCPP
}
// loglik_bastide_eigen
double loglik_bastide_eigen(const Eigen::MatrixXd& R, const Eigen::MatrixXd& S, const Eigen::MatrixXi& edge, const Eigen::VectorXd& edge_length, const Eigen::MatrixXd& traits, const Eigen::VectorXi& species_idx, int n_tips, int n_nodes);
RcppExport SEXP _phylopars_pyport_loglik_bastide_eigen(SEXP RSEXP, SEXP SSEXP, SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP traitsSEXP, SEXP species_idxSEXP, SEXP n_tipsSEXP, SEXP n_nodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXi& >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type traits(traitsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type species_idx(species_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_tips(n_tipsSEXP);
    Rcpp::traits::input_parameter< int >::type n_nodes(n_nodesSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_bastide_eigen(R, S, edge, edge_length, traits, species_idx, n_tips, n_nodes));
    return rcpp_result_gen;
END_RCPP
}
// bastide_gradient_eigen
List bastide_gradient_eigen(const Eigen::MatrixXd& R, const Eigen::MatrixXd& S, const Eigen::MatrixXi& edge, const Eigen::VectorXd& edge_length, const Eigen::MatrixXd& traits, const Eigen::VectorXi& species_idx, int n_tips, int n_nodes);
RcppExport SEXP _phylopars_pyport_bastide_gradient_eigen(SEXP RSEXP, SEXP SSEXP, SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP traitsSEXP, SEXP species_idxSEXP, SEXP n_tipsSEXP, SEXP n_nodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXi& >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type traits(traitsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type species_idx(species_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_tips(n_tipsSEXP);
    Rcpp::traits::input_parameter< int >::type n_nodes(n_nodesSEXP);
    rcpp_result_gen = Rcpp::wrap(bastide_gradient_eigen(R, S, edge, edge_length, traits, species_idx, n_tips, n_nodes));
    return rcpp_result_gen;
END_RCPP
}
// em_fit_eigen
List em_fit_eigen(const Eigen::MatrixXd& R_init, const Eigen::MatrixXd& S_init, const Eigen::VectorXd& mu_init, const Eigen::MatrixXi& edge, const Eigen::VectorXd& edge_length, const Eigen::MatrixXd& traits, const Eigen::VectorXi& species_idx, int n_tips, int n_nodes, int max_iter, double tol, bool verbose);
RcppExport SEXP _phylopars_pyport_em_fit_eigen(SEXP R_initSEXP, SEXP S_initSEXP, SEXP mu_initSEXP, SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP traitsSEXP, SEXP species_idxSEXP, SEXP n_tipsSEXP, SEXP n_nodesSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type R_init(R_initSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type S_init(S_initSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type mu_init(mu_initSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXi& >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type traits(traitsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type species_idx(species_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_tips(n_tipsSEXP);
    Rcpp::traits::input_parameter< int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(em_fit_eigen(R_init, S_init, mu_init, edge, edge_length, traits, species_idx, n_tips, n_nodes, max_iter, tol, verbose));
    return rcpp_result_gen;
END_RCPP
}
// restricted_loglik_arma
double restricted_loglik_arma(const arma::mat& Sigma, const arma::mat& B, const arma::imat& edge, const arma::vec& edge_length, const arma::mat& traits, const arma::ivec& species_idx, int n_obs, int Nnode);
RcppExport SEXP _phylopars_pyport_restricted_loglik_arma(SEXP SigmaSEXP, SEXP BSEXP, SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP traitsSEXP, SEXP species_idxSEXP, SEXP n_obsSEXP, SEXP NnodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type traits(traitsSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type species_idx(species_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_obs(n_obsSEXP);
    Rcpp::traits::input_parameter< int >::type Nnode(NnodeSEXP);
    rcpp_result_gen = Rcpp::wrap(restricted_loglik_arma(Sigma, B, edge, edge_length, traits, species_idx, n_obs, Nnode));
    return rcpp_result_gen;
END_RCPP
}
// restricted_loglik_eigen
double restricted_loglik_eigen(const Eigen::MatrixXd& Sigma, const Eigen::MatrixXd& B, const Eigen::MatrixXi& edge, const Eigen::VectorXd& edge_length, const Eigen::MatrixXd& traits, const Eigen::VectorXi& species_idx, int n_obs, int Nnode);
RcppExport SEXP _phylopars_pyport_restricted_loglik_eigen(SEXP SigmaSEXP, SEXP BSEXP, SEXP edgeSEXP, SEXP edge_lengthSEXP, SEXP traitsSEXP, SEXP species_idxSEXP, SEXP n_obsSEXP, SEXP NnodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXi& >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type traits(traitsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type species_idx(species_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_obs(n_obsSEXP);
    Rcpp::traits::input_parameter< int >::type Nnode(NnodeSEXP);
    rcpp_result_gen = Rcpp::wrap(restricted_loglik_eigen(Sigma, B, edge, edge_length, traits, species_idx, n_obs, Nnode));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_phylopars_pyport_loglik_bastide_arma", (DL_FUNC) &_phylopars_pyport_loglik_bastide_arma, 8},
    {"_phylopars_pyport_bastide_gradient_arma", (DL_FUNC) &_phylopars_pyport_bastide_gradient_arma, 8},
    {"_phylopars_pyport_em_fit_arma", (DL_FUNC) &_phylopars_pyport_em_fit_arma, 12},
    {"_phylopars_pyport_loglik_bastide_eigen", (DL_FUNC) &_phylopars_pyport_loglik_bastide_eigen, 8},
    {"_phylopars_pyport_bastide_gradient_eigen", (DL_FUNC) &_phylopars_pyport_bastide_gradient_eigen, 8},
    {"_phylopars_pyport_em_fit_eigen", (DL_FUNC) &_phylopars_pyport_em_fit_eigen, 12},
    {"_phylopars_pyport_restricted_loglik_arma", (DL_FUNC) &_phylopars_pyport_restricted_loglik_arma, 8},
    {"_phylopars_pyport_restricted_loglik_eigen", (DL_FUNC) &_phylopars_pyport_restricted_loglik_eigen, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_phylopars_pyport(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
