# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bastide Traversal (Forward Only) - Armadillo
#'
#' Computes ML log-likelihood using Bastide 2021 algorithm.
#' This is the forward pass only (tips to root).
#'
#' @param R Phylogenetic rate matrix (p x p)
#' @param S Residual covariance matrix (p x p)
#' @param edge Edge matrix from phylo object (n_edges x 2), 1-indexed
#' @param edge_length Edge lengths vector
#' @param traits Trait matrix (nind x p), NA for missing
#' @param species_idx Species index for each observation (1-indexed tip node)
#' @param n_tips Number of tip species
#' @param n_nodes Total number of nodes (tips + internal)
#'
#' @return ML log-likelihood value
#' @export
loglik_bastide_arma <- function(R, S, edge, edge_length, traits, species_idx, n_tips, n_nodes) {
    .Call(`_phylopars_pyport_loglik_bastide_arma`, R, S, edge, edge_length, traits, species_idx, n_tips, n_nodes)
}

#' Bastide Gradient Computation - Armadillo
#'
#' Computes likelihood and analytic gradients using Bastide 2021 algorithm.
#' Runs both forward pass (for likelihood) and backward pass (for gradients).
#'
#' @param R Phylogenetic rate matrix (p x p)
#' @param S Residual covariance matrix (p x p)
#' @param edge Edge matrix from phylo object (n_edges x 2), 1-indexed
#' @param edge_length Edge lengths vector
#' @param traits Trait matrix (nind x p), NA for missing
#' @param species_idx Species index for each observation (1-indexed tip node)
#' @param n_tips Number of tip species
#' @param n_nodes Total number of nodes (tips + internal)
#'
#' @return List with logL, mu, grad_R, grad_S
#' @export
bastide_gradient_arma <- function(R, S, edge, edge_length, traits, species_idx, n_tips, n_nodes) {
    .Call(`_phylopars_pyport_bastide_gradient_arma`, R, S, edge, edge_length, traits, species_idx, n_tips, n_nodes)
}

#' EM Algorithm - Armadillo
#'
#' Full EM algorithm for phylogenetic mixed models.
#'
#' @param R_init Initial phylogenetic rate matrix
#' @param S_init Initial residual covariance matrix
#' @param mu_init Initial mean vector
#' @param edge Edge matrix (n_edges x 2), 1-indexed
#' @param edge_length Edge lengths
#' @param traits Trait matrix (nind x p)
#' @param species_idx Species index for each observation (1-indexed)
#' @param n_tips Number of tips
#' @param n_nodes Total nodes
#' @param max_iter Maximum iterations
#' @param tol Convergence tolerance
#' @param verbose Print progress
#'
#' @return List with R, S, mu, logL, converged, iterations
#' @export
em_fit_arma <- function(R_init, S_init, mu_init, edge, edge_length, traits, species_idx, n_tips, n_nodes, max_iter = 100L, tol = 1e-6, verbose = FALSE) {
    .Call(`_phylopars_pyport_em_fit_arma`, R_init, S_init, mu_init, edge, edge_length, traits, species_idx, n_tips, n_nodes, max_iter, tol, verbose)
}

#' Bastide Traversal (Forward Only) - Eigen
#'
#' Computes ML log-likelihood using Bastide 2021 algorithm (Eigen implementation).
#'
#' @param R Phylogenetic rate matrix (p x p)
#' @param S Residual covariance matrix (p x p)
#' @param edge Edge matrix from phylo object (n_edges x 2), 1-indexed
#' @param edge_length Edge lengths vector
#' @param traits Trait matrix (nind x p), NA for missing
#' @param species_idx Species index for each observation (1-indexed tip node)
#' @param n_tips Number of tip species
#' @param n_nodes Total number of nodes (tips + internal)
#'
#' @return ML log-likelihood value
#' @export
loglik_bastide_eigen <- function(R, S, edge, edge_length, traits, species_idx, n_tips, n_nodes) {
    .Call(`_phylopars_pyport_loglik_bastide_eigen`, R, S, edge, edge_length, traits, species_idx, n_tips, n_nodes)
}

#' Bastide Gradient Computation - Eigen
#'
#' Computes likelihood and analytic gradients (Eigen implementation).
#'
#' @param R Phylogenetic rate matrix (p x p)
#' @param S Residual covariance matrix (p x p)
#' @param edge Edge matrix from phylo object (n_edges x 2), 1-indexed
#' @param edge_length Edge lengths vector
#' @param traits Trait matrix (nind x p), NA for missing
#' @param species_idx Species index for each observation (1-indexed tip node)
#' @param n_tips Number of tip species
#' @param n_nodes Total number of nodes (tips + internal)
#'
#' @return List with logL, mu, grad_R, grad_S
#' @export
bastide_gradient_eigen <- function(R, S, edge, edge_length, traits, species_idx, n_tips, n_nodes) {
    .Call(`_phylopars_pyport_bastide_gradient_eigen`, R, S, edge, edge_length, traits, species_idx, n_tips, n_nodes)
}

#' EM Algorithm - Eigen
#'
#' Full EM algorithm (Eigen implementation).
#'
#' @param R_init Initial phylogenetic rate matrix
#' @param S_init Initial residual covariance matrix
#' @param mu_init Initial mean vector
#' @param edge Edge matrix (n_edges x 2), 1-indexed
#' @param edge_length Edge lengths
#' @param traits Trait matrix (nind x p)
#' @param species_idx Species index for each observation (1-indexed)
#' @param n_tips Number of tips
#' @param n_nodes Total nodes
#' @param max_iter Maximum iterations
#' @param tol Convergence tolerance
#' @param verbose Print progress
#'
#' @return List with R, S, mu, logL, converged, iterations
#' @export
em_fit_eigen <- function(R_init, S_init, mu_init, edge, edge_length, traits, species_idx, n_tips, n_nodes, max_iter = 100L, tol = 1e-6, verbose = FALSE) {
    .Call(`_phylopars_pyport_em_fit_eigen`, R_init, S_init, mu_init, edge, edge_length, traits, species_idx, n_tips, n_nodes, max_iter, tol, verbose)
}

#' Restricted log-likelihood using RcppArmadillo
#'
#' Fast C++ implementation of the postorder tree traversal algorithm.
#'
#' @param Sigma Phylogenetic covariance matrix (m x m)
#' @param B Residual covariance matrix (m x m)
#' @param edge Edge matrix from phylo object (n_edges x 2), 1-indexed
#' @param edge_length Edge lengths vector
#' @param traits Trait matrix (nind x m), NA for missing
#' @param species_idx Species index for each observation (1-indexed tip node)
#' @param n_obs Total number of non-missing observations
#' @param Nnode Total number of nodes (tips + internal)
#'
#' @return Log-likelihood value, or -1e100 if singular
#' @export
restricted_loglik_arma <- function(Sigma, B, edge, edge_length, traits, species_idx, n_obs, Nnode) {
    .Call(`_phylopars_pyport_restricted_loglik_arma`, Sigma, B, edge, edge_length, traits, species_idx, n_obs, Nnode)
}

#' Restricted log-likelihood using RcppEigen
#'
#' Fast C++ implementation using Eigen library.
#'
#' @param Sigma Phylogenetic covariance matrix (m x m)
#' @param B Residual covariance matrix (m x m)
#' @param edge Edge matrix from phylo object (n_edges x 2), 1-indexed
#' @param edge_length Edge lengths vector
#' @param traits Trait matrix (nind x m), NA for missing
#' @param species_idx Species index for each observation (1-indexed tip node)
#' @param n_obs Total number of non-missing observations
#' @param Nnode Total number of nodes (tips + internal)
#'
#' @return Log-likelihood value, or -1e100 if singular
#' @export
restricted_loglik_eigen <- function(Sigma, B, edge, edge_length, traits, species_idx, n_obs, Nnode) {
    .Call(`_phylopars_pyport_restricted_loglik_eigen`, Sigma, B, edge, edge_length, traits, species_idx, n_obs, Nnode)
}

